spring:
  datasource:
    # deploy
    url: jdbc:opengauss://192.168.0.237:26000/dip2207
    driver-class-name: org.opengauss.Driver
    # local
#    url: jdbc:opengauss://114.116.245.5:26000/dip2207
#    driver-class-name: org.opengauss.Driver
    username: winston
    password: gauss@123
  jackson:
     time-zone: GMT+8
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 7721
